### ISSUE TITLE
Multiple DPDK devices

### ISSUE THREAD

**Issue by lapnd** [krsacme/tht-dpdk#14]
Hello Saravanan,
As I understand, if I want to use another NIC as DPDK device, I need add new section like this
```sh
type: ovs_user_bridge
              name: br-link
              use_dhcp: false
              members:
                -
                  type: ovs_dpdk_port
                  name: dpdk0
                  members:
                    -
                      type: interface
                      name: nic5

                  type: ovs_dpdk_port
                  name: dpdk1
                  members:
                    -
                      type: interface
                      name: nic6
```

and after overcloud is deployed, I want to test VM with topo as:
![image](https://cloud.githubusercontent.com/assets/17825933/26711397/31e74f96-478a-11e7-8c42-2e71d0d60bf3.png)

To do that, I need to create two tenant networks 
- Tenant 1 is associated with dpdk0 (NIC5)
- Tenant 2 is associated with dpdk1 (NIC6)
so that a new VM can be launched with two different tenant networks

```sh
dpdk0_net=$(neutron net-list | awk ' /tenant0/ {print $2;}')
dpdk1_net=$(neutron net-list | awk ' /tenant1/ {print $2;}')
nova boot --flavor m1.nano \
        --nic net-id=$dpdk0_net \
        --nic net-id=$dpdk1_net \
        --image rhel --key-name test  dpdk1
```

Could you please tell me how to create these two tenant networks?

Thank you!

**Comment by lapnd** [comment]
Hi Saravanan, 
Never mind,
This repo https://github.com/redhat-performance/openstack-templates give an example on using multiple DPDK devices

**Comment by krsacme** [comment]
Just to clarify on the terms, it is not a tenant network, it should be provider network.
